A5Patients/A5Patients/ALPatients/Controllers/ALCountryController.cs
/* ALPatients
 * Version 5
 * Abiey-Lema, 2019.12.01: Created
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ALPatients.Models;
using Microsoft.AspNetCore.Authorization;

namespace ALPatients.Controllers
{
    /* ALCountryController Controls flow of information for the views of the Country Pages. 
    * Handles URL Requests for the Country Pages. Gets Data From The Pateints  Database for the 
    * Country Table using the generated models for Country Table
    */


    [Authorize(Roles = "members")]
    public class ALCountryController : Controller
    {
        private readonly PatientsContext _context;
        
        
        public ALCountryController(PatientsContext context)
        {
            _context = context;
        }

        // Perform Database Access - Get Country Table From Patients Database and list all records
        //and returns view to index
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Country.ToListAsync());
        }

        // shows all fields for the selected record
        
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.CountryCode == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // Display Blank Input Page and configure drop downs for foreign keys
        [Authorize(Roles = "administrators, medicalStaff")]
        public IActionResult Create()
        {
            return View();
        }

        // Adds new record to the table
        // Differentiated by receiving parameters
        //attribute restricts this to a <form> with action="POST" to enbale only the properties we want to bind to
        [Authorize(Roles = "administrators, medicalStaff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountryCode,Name,PostalPattern,PhonePattern,FederalSalesTax")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }


        // display the selected record for updating
        [Authorize(Roles = "administrators, medicalStaff")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // requiring HTTP POST, to save the updated record to the table
        //  look for the listed variable names in the flow from the browser and prevent injection
        [Authorize(Roles = "administrators, medicalStaff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CountryCode,Name,PostalPattern,PhonePattern,FederalSalesTax")] Country country)
        {
            if (id != country.CountryCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.CountryCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // Display the selected record to confirm the delete
        [Authorize(Roles = "administrators, medicalStaff")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.CountryCode == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // requiring HTTP POST, to delete the record after confirmation
        [Authorize(Roles = "administrators, medicalStaff")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var country = await _context.Country.FindAsync(id);
            _context.Country.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // If incoming (string) field can't be converted to the expected primitive datatype..
        // Binder will map parameters by name to fields in the flow from the browser

        private bool CountryExists(string id)
        {
            return _context.Country.Any(e => e.CountryCode == id);
        }
    }
}

A5Patients/A5Patients/ALPatients/Controllers/ALRoleController.cs
/* ALPatients
 * Version 5
 * Abiey-Lema, 2019.12.01: Created
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace A5Patients.Controllers
{
    [Authorize(Roles = "administrators")]
    public class ALRoleController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        //Constructor for creating roleManager and userManager objects
        public ALRoleController(UserManager<IdentityUser> userManager,
           RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        // Method for Index Action of ALRoleController 
        //list all current roles, links to manage roles

        public IActionResult Index()
        {
            var
             roles = roleManager.Roles.OrderBy(a => a.Name);
            return
             View(roles);
        }

        //Method with PostBack action to create new roles 
        [HttpPost]
        public async Task<IActionResult> Create(string roleName)
        {
           

            if (string.IsNullOrWhiteSpace(roleName))
            {
                TempData["message"] = "Role Name cannot be empty or blanks";

            }

            else if (await roleManager.RoleExistsAsync(roleName))
            {
                TempData["message"] = "Role name is already on file";

            }

            else
            {






                try
                {


                    IdentityResult identityResult =
                        await roleManager.CreateAsync(new IdentityRole(roleName));
                    if (!identityResult.Succeeded)

                        throw new Exception(identityResult.Errors.FirstOrDefault().Description);
                    TempData["message"] = $"role created: '{roleName}'";




                }
                catch (Exception ex)
                {

                    TempData["message"] = "exception creating role: " + ex.GetBaseException().Message;
                }
            }



            return RedirectToAction(nameof(Index));

        }

        //Method to delete roles 
        
        public async Task<IActionResult> DeleteRole(string roleName)
        {


            if (string.IsNullOrWhiteSpace(roleName))
            {
                TempData["message"] = "Role Name cannot be empty or blanks";

            }

            else if (!await roleManager.RoleExistsAsync(roleName))
            {
                TempData["message"] = "Role name cannot be found";

            }

            else
            {






                try
                {


                    var role =
                        await roleManager.FindByNameAsync(roleName);
                    IdentityResult result = await roleManager.DeleteAsync(role);
                    if (!result.Succeeded)

                        throw new Exception(result.Errors.FirstOrDefault().Description);
                    TempData["message"] = $"role deleted: '{roleName}'";




                }
                catch (Exception ex)
                {

                    TempData["message"] = "exception deleting role: " + ex.GetBaseException().Message;
                }
            }



            return RedirectToAction(nameof(Index));

        }

        //Method with PostBack action to add users to roles 
        [HttpPost]
        public async Task<IActionResult> AddToRoles(string roleName)
        {
            string userName = User.Identity.Name;

            IdentityUser currentUser = await userManager.FindByNameAsync(userName);

            await userManager.AddToRoleAsync(currentUser, roleName);








            return RedirectToAction(nameof(Index));

        }

        
        public async Task<IActionResult> RemoveUserFromRole(string userName, string roleName)
        {
            

            IdentityUser currentUser = await userManager.FindByNameAsync(userName);
            IdentityResult addResult = await userManager.RemoveFromRoleAsync(currentUser, roleName);

            await userManager.RemoveFromRoleAsync(currentUser, roleName);








            return Redirect(nameof(UsersInRole));

        }

        //Method to list all users in a given role

        public async Task<IActionResult> UsersInRole(string roleName)
        {
            if (roleName !=null)
            {
                HttpContext.Session.SetString("roleName", roleName);

            }

            else
            {
                roleName = HttpContext.Session.GetString("roleName"); 

            }
            var usersInRole = await userManager.GetUsersInRoleAsync(roleName);
            var allUsers = userManager.Users;
            List<IdentityUser> userNotInRole = new List<IdentityUser>();

            foreach (var item in allUsers)
            {
                if (!usersInRole.Contains(item))
                {
                    userNotInRole.Add(item);
                    
                }

            }



            ViewData["notInRole"] = new SelectList(userNotInRole,  "UserName");
            

            return View(usersInRole);
        }

        //Method to add users to a role
        public async Task<IActionResult> AddUserToRole(string userName)
        {
            string roleName = HttpContext.Session.GetString("roleName");
            var user = await userManager.FindByNameAsync(userName);

            try
            {
                IdentityResult result = await userManager.AddToRoleAsync(user, roleName);
                if (!result.Succeeded)
                {
                    throw new Exception(result.Errors.First().Description);

                }

                TempData["message"] = $"User added to role";
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.GetBaseException().Message;

                
            }




            return RedirectToAction("usersInRole");



        }
    }
}

A5Patients/A5Patients/ALPatients/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ALPatients</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    .mynavbar {
        overflow: hidden;
        background-color: white;
    }

        .mynavbar a {
            float: left;
            font-size: 16px;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

    .mydropdown {
        float: left;
        overflow: hidden;
    }

        .mydropdown .mydropbtn {
            font-size: 16px;
            border: none;
            outline: none;
            color: black;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }

        .mynavbar a:hover, .mydropdown:hover .mydropbtn {
            background-color: white;
        }

    .mydropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .mydropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

            .mydropdown-content a:hover {
                background-color: #ddd;
            }

    .mydropdown:hover .mydropdown-content {
        display: block;
    }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ALPatients</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                      
                    </ul>
                    <div class="mynavbar">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ALCountry" asp-action="Index">Country</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="ALPatient" asp-action="Index">Patients</a>
                        @if (User.IsInRole("administrators"))
                        {
                        <div class="mydropdown">
                            <button class="mydropbtn">
                                Security
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mydropdown-content">
                                <a href="#">User Maintenance</a>

                                <a asp-controller="ALRole" asp-action="Index">Role Maintenance</a>

                            </div>
                        </div>
                        }
                    </div>
                </div>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <span style="font-weight: bold; color: red;">@TempData["message"]</span>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - <a href="mailto:alema1695@conestogac.on.ca">Abiey Lema</a> - Section 1
            <span style="float: right;">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </span>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>